/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Backend {
  entities: {
    Client: Client;
    Case: Case;
    Document: Document;
    Message: Message;
    Invoice: Invoice;
    LegalRecommendation: LegalRecommendation;
    ClientLoginHistory: ClientLoginHistory;
    PasswordChangeHistory: PasswordChangeHistory;
    Partner: Partner;
    PartnerLoginHistory: PartnerLoginHistory;
    Collaborator: Collaborator;
    PrivateLead: PrivateLead;
    [k: string]: unknown;
  };
  auth: {
    providers: string[];
    [k: string]: unknown;
  };
  firestore?: {
    structure: {
      path: string;
      definition: {
        entityName: string;
        schema: {
          [k: string]: unknown;
        };
        description: string;
        params: {
          name: string;
          description: string;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }[];
    reasoning: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Represents a client of Giffoni Advogados Associados.
 */
export interface Client {
  /**
   * Unique identifier for the Client entity.
   */
  id: string;
  /**
   * First name of the client.
   */
  firstName: string;
  /**
   * Last name of the client.
   */
  lastName: string;
  /**
   * Email address of the client.
   */
  email: string;
  /**
   * Phone number of the client.
   */
  phone?: string;
  /**
   * Address of the client.
   */
  address?: string;
  [k: string]: unknown;
}
/**
 * Represents a legal case.
 */
export interface Case {
  /**
   * Unique identifier for the Case entity.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N Case)
   */
  clientId: string;
  /**
   * Name or title of the case.
   */
  caseName: string;
  /**
   * Description of the case.
   */
  description?: string;
  /**
   * Current status of the case (e.g., 'Open', 'In Progress', 'Closed').
   */
  status: string;
  /**
   * Date the case was opened.
   */
  openDate: string;
  [k: string]: unknown;
}
/**
 * Represents a legal document related to a case.
 */
export interface Document {
  /**
   * Unique identifier for the Document entity.
   */
  id: string;
  /**
   * Reference to Case. (Relationship: Case 1:N Document)
   */
  caseId: string;
  /**
   * Name of the document.
   */
  documentName: string;
  /**
   * URL or path to the document file.
   */
  fileUrl: string;
  /**
   * Date the document was uploaded.
   */
  uploadDate: string;
  [k: string]: unknown;
}
/**
 * Represents a message exchanged between a client and the legal team.
 */
export interface Message {
  /**
   * Unique identifier for the Message entity.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N Message)
   */
  clientId: string;
  /**
   * Sender of the message (Client or Lawyer).
   */
  sender: string;
  /**
   * Content of the message.
   */
  messageText: string;
  /**
   * Timestamp of when the message was sent.
   */
  timestamp: string;
  [k: string]: unknown;
}
/**
 * Represents an invoice for legal services.
 */
export interface Invoice {
  /**
   * Unique identifier for the Invoice entity.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N Invoice)
   */
  clientId: string;
  /**
   * Invoice number.
   */
  invoiceNumber: string;
  /**
   * Date the invoice was issued.
   */
  issueDate: string;
  /**
   * Date the invoice is due.
   */
  dueDate: string;
  /**
   * Total amount of the invoice.
   */
  amount: number;
  /**
   * Status of the invoice (e.g., 'Paid', 'Unpaid', 'Overdue').
   */
  status: string;
  /**
   * URL or path to the invoice PDF file.
   */
  pdfUrl: string;
  [k: string]: unknown;
}
/**
 * Represents a personalized legal recommendation based on case documents and customer profile data.
 */
export interface LegalRecommendation {
  /**
   * Unique identifier for the LegalRecommendation entity.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N LegalRecommendation)
   */
  clientId: string;
  /**
   * Reference to Document. (Relationship: Document 1:N LegalRecommendation)
   */
  documentId: string;
  /**
   * The actual legal recommendation.
   */
  recommendationText: string;
  /**
   * Date the recommendation was generated.
   */
  recommendationDate: string;
  [k: string]: unknown;
}
/**
 * Represents the login history of a client.
 */
export interface ClientLoginHistory {
  /**
   * Unique identifier for the ClientLoginHistory entry.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N ClientLoginHistory)
   */
  clientId: string;
  /**
   * Timestamp of when the client logged in.
   */
  loginTimestamp: string;
  /**
   * IP address from which the client logged in.
   */
  ipAddress: string;
  /**
   * User agent of the client's browser.
   */
  userAgent?: string;
  [k: string]: unknown;
}
/**
 * Represents the password change history of a client.
 */
export interface PasswordChangeHistory {
  /**
   * Unique identifier for the PasswordChangeHistory entry.
   */
  id: string;
  /**
   * Reference to Client. (Relationship: Client 1:N PasswordChangeHistory)
   */
  clientId: string;
  /**
   * Timestamp of when the password was changed.
   */
  changeTimestamp: string;
  /**
   * Who changed the password (e.g., 'Client', 'Admin').
   */
  changedBy: string;
  [k: string]: unknown;
}
/**
 * Represents a partner of Giffoni Advogados Associados.
 */
export interface Partner {
  /**
   * Unique identifier for the Partner entity, matches Firebase Auth UID.
   */
  id: string;
  /**
   * Full name of the partner.
   */
  name: string;
  /**
   * Company the partner represents.
   */
  company: string;
  /**
   * The partner's role or position.
   */
  role: string;
  /**
   * Email address of the partner.
   */
  email: string;
  /**
   * Timestamp of when the partner was registered.
   */
  createdAt: string;
  /**
   * Nationality of the partner.
   */
  nationality?: string;
  /**
   * Marital status of the partner.
   */
  maritalStatus?: string;
  /**
   * RG (ID card) of the partner.
   */
  rg?: string;
  /**
   * CPF (taxpayer ID) of the partner.
   */
  cpf?: string;
  /**
   * OAB (Brazilian Bar Association) registration number, if applicable.
   */
  oabNumber?: string;
  /**
   * Full address of the partner.
   */
  address?: string;
  /**
   * Contact phone number of the partner.
   */
  phone?: string;
  /**
   * Instagram profile handle.
   */
  instagram?: string;
  /**
   * TikTok profile handle.
   */
  tiktok?: string;
  /**
   * Facebook profile URL.
   */
  facebook?: string;
  /**
   * Banking information for payments.
   */
  bankDetails?: {
    /**
     * The Pix key.
     */
    pixKey?: string;
    /**
     * The type of the Pix key.
     */
    pixKeyType?: "CPF/CNPJ" | "Celular" | "E-mail" | "Aleatória";
    /**
     * The name of the bank.
     */
    bankName?: string;
    /**
     * The bank agency number.
     */
    agency?: string;
    /**
     * The bank account number.
     */
    accountNumber?: string;
    /**
     * The type of bank account.
     */
    accountType?: "Corrente" | "Poupança";
    /**
     * Full name of the account holder.
     */
    accountHolderName?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Represents the login history of a partner.
 */
export interface PartnerLoginHistory {
  /**
   * Unique identifier for the PartnerLoginHistory entry.
   */
  id: string;
  /**
   * Reference to Partner. (Relationship: Partner 1:N PartnerLoginHistory)
   */
  partnerId: string;
  /**
   * Timestamp of when the partner logged in.
   */
  loginTimestamp: string;
  /**
   * IP address from which the partner logged in.
   */
  ipAddress: string;
  /**
   * User agent of the partner's browser.
   */
  userAgent?: string;
  [k: string]: unknown;
}
/**
 * Represents an internal collaborator of Giffoni Advogados Associados.
 */
export interface Collaborator {
  /**
   * Unique identifier for the collaborator, matches Firebase Auth UID.
   */
  uid: string;
  /**
   * Full name of the collaborator.
   */
  name: string;
  /**
   * Email address for login.
   */
  email: string;
  /**
   * Professional contact email.
   */
  professionalEmail?: string;
  /**
   * Nationality of the collaborator.
   */
  nationality?: string;
  /**
   * Marital status of the collaborator.
   */
  maritalStatus?: string;
  /**
   * The role or type of the collaborator.
   */
  collaboratorType: "Advogado" | "Estagiário" | "Secretaria" | "Perito";
  /**
   * OAB number, required if collaboratorType is 'Advogado'.
   */
  oabNumber?: string;
  /**
   * The state of the OAB registration.
   */
  oabState?: string;
  /**
   * Details about the university, applicable only if collaboratorType is 'Estagiário'.
   */
  universityDetails?: {
    universityName?: string;
    universityPhone?: string;
    universityEmail?: string;
    currentSemester?: string;
    internshipType?: "obrigatorio" | "nao_obrigatorio";
    [k: string]: unknown;
  };
  /**
   * Area of expertise, applicable only if collaboratorType is 'Perito'.
   */
  expertiseArea?: string;
  /**
   * Full residential address of the collaborator.
   */
  address?: {
    street?: string;
    number?: string;
    complement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    [k: string]: unknown;
  };
  /**
   * Contact phone number.
   */
  phone?: string;
  /**
   * Banking information for payments.
   */
  bankDetails?: {
    pixKey?: string;
    pixKeyType?: "CPF/CNPJ" | "Celular" | "E-mail" | "Aleatória";
    bankName?: string;
    agency?: string;
    accountNumber?: string;
    accountType?: "Corrente" | "Poupança";
    accountHolderName?: string;
    [k: string]: unknown;
  };
  /**
   * Timestamp of when the collaborator was registered.
   */
  createdAt: string;
  [k: string]: unknown;
}
/**
 * Represents a potential private client lead captured from the BOSS portal.
 */
export interface PrivateLead {
  /**
   * Unique identifier for the lead.
   */
  id: string;
  /**
   * Full name of the potential client.
   */
  fullName: string;
  /**
   * Contact phone number of the lead.
   */
  phone?: string;
  /**
   * Indicates if the phone number has WhatsApp.
   */
  hasWhatsapp?: boolean;
  /**
   * Instagram handle of the lead.
   */
  instagram?: string;
  /**
   * Facebook profile URL of the lead.
   */
  facebook?: string;
  /**
   * TikTok handle of the lead.
   */
  tiktok?: string;
  /**
   * Timestamp of when the lead was created.
   */
  createdAt: string;
  [k: string]: unknown;
}
